package avalon.model.items.material;

public enum EffectType {
    ADDED_FIRE_DAMAGE,
    ADDED_ICE_DAMAGE,
    ADDED_LIGHTNING_DAMAGE,
    ADDED_PIERCING_DAMAGE,
    ADDED_SLASHING_DAMAGE,
    ADDED_BLUNT_DAMAGE,
    ADDED_HOLY_DAMAGE,
    ADDED_DARK_DAMAGE,

    LESS_FIRE_DAMAGE,
    LESS_ICE_DAMAGE,
    LESS_LIGHTNING_DAMAGE,
    LESS_PIERCING_DAMAGE,
    LESS_SLASHING_DAMAGE,
    LESS_BLUNT_DAMAGE,
    LESS_HOLY_DAMAGE,
    LESS_DARK_DAMAGE,

    ADDED_FIRE_RESIST,
    ADDED_ICE_RESIST,
    ADDED_LIGHTNING_RESIST,
    ADDED_PIERCING_RESIST,
    ADDED_SLASHING_RESIST,
    ADDED_BLUNT_RESIST,
    ADDED_HOLY_RESIST,
    ADDED_DARK_RESIST,

    LESS_FIRE_RESIST,
    LESS_ICE_RESIST,
    LESS_LIGHTNING_RESIST,
    LESS_PIERCING_RESIST,
    LESS_SLASHING_RESIST,
    LESS_BLUNT_RESIST,
    LESS_HOLY_RESIST,
    LESS_DARK_RESIST,

}
